version: "3.7"

services:
  word-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: word-server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'

volumes:
  data:
    driver: local