# definitions
definitions:
  wordbook:
    type: object
    required:
      - title
      - owner
      - words
    properties:
      _id: 
        type: string
        format: ObjectId
        description: wordbook Id
      title: 
        type: string
        description: wordbook title
      owner: 
        type: integer
        description: wordbook owner
      createdAt:
        type: string
        format: date-time
        description: wordbook created date
      updatedAt: 
        type: string
        format: date-time
        description: wordbook updated date
      words: 
        type: object
        properties:
          wordId:
            $ref: '#/definitions/word'
          isRemoved:
            type: boolean
            description: Whether to delete
          filter: 
            type: string
            enum: [doNotKnow, memorized, confused]
            description: word filtering
          addedAt: 
            type: string
            format: date-time
            description: word added date-time
      
  word: 
    type: object
    required:
      - word
      - meanings
      - wordClasses
      - phonics
      - pronounceVoicePath
    properties:
      _id: 
        type: string
        format: ObjectId
        description: word Id
      word: 
        type: string
        description: word
      wordClasses:
        type: string
        enum: [nouns, pronouns, verbs, adverbs, adjective, articles, prepositions, conjunctions, interjections]
      phonics:
        type: string
        description: word phonics
      pronounceVoicePath: 
        type: string
        description: word pronounceVoicePath

schemes:
  - https
  - http
